spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5544/kontrolltoo2
spring.datasource.username=postgres
spring.datasource.password=Argv106munk106
