# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5544/Library
spring.datasource.username=postgres
spring.datasource.password=Argv106munk106

spring.web.resources.static-locations=file:/home/fahis/Desktop/Library/uploads/,classpath:/static/

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Server Configuration
# ===============================
server.port=8080